every 1 minute:

	set {_now} to unix timestamp of now

	loop indices of {mute::*}:
		if {_now} >= {mute::%loop-value%}:

			delete {mute::%loop-value%}
			set {_p} to loop-value parsed as offlineplayer

			if {_p} is online:

				send "" to {_p}
				send server_feedback("success", "&fA némításod ßfel lett oldva&f!") to {_p}
				send server_feedback("success", "&fMost már újra írhatsz a chatre!") to {_p}
				send "" to {_p}