on inventory click:

	# Lekérdezzük melyik oldalt járt a játékos
	set {_page} to (metadata "shop_gui_page" of player)
	if {_page} is set:
		cancel event

		# A Shop mérete
		set {_size} to {config::shop::size}

		# Egy sor 9 slotból áll
		set {_steps} to 9

		# Előre lapozást kezelő item slotja
		set {_slot::forward} to ({_size} * {_steps}) - 4
		# Hátra lapozást kezelő item slotja
		set {_slot::backward} to ({_size} * {_steps}) - 6

		# Visszafele lapozás
		if all:
			index of event-slot = {_slot::backward}
			event-item = {config::shop::item::page}

		then:
			# Módosítjuk az oldal számlálóját
			set {_page} to (metadata "shop_gui_page" of player) - 1
			set (metadata "shop_gui_page" of player) to {_page}
			# Frissítjük a tárgyakat
			shop_gui_refresh(player, {_page})

		# Előrefele lapozás
		if all:
			index of event-slot = {_slot::forward}
			event-item = {config::shop::item::page}

		then:
			# Módosítjuk az oldal számlálóját
			set {_page} to (metadata "shop_gui_page" of player) + 1
			set (metadata "shop_gui_page" of player) to {_page}
			# Frissítjük a tárgyakat
			shop_gui_refresh(player, {_page})

		else:
			# Tárgyak, amiket egy játékos rakott fel
			set {_nbt} to custom nbt compound of event-slot
			if int tag "Shop;ID" of {_nbt} is set:

				# Ha az eladó az a játékos
				if (string tag "Shop;Seller" of {_nbt}) = player:
					# Tárgy levétel
					shop_item_remove(player, event-slot)
				else:
					# Tárgy vásárlás
					shop_item_purchase(player, event-slot)