options:
	shop-name: "%display_name({_owner})% &8boltja"

function shop_gui_open(p: player, owner: offlineplayer, page: integer, global: boolean = false):

	# Shop mérete
	set {_size} to {config::shop::size}
	set {_steps} to 9

	# Dinamikusan kiszámoljuk, hova rakjuk a filler blockokat
	set {_first_row::first} to 0
	set {_first_row::last} to {_steps}

	set {_last_row::last} to {_size} * {_steps} - 1
	set {_last_row::first} to {_last_row::last} - ({_steps} - 1)

	# Létrehozunk egy GUI-t
	set {_gui} to chest inventory with {_size} rows named {@shop-name}

	# Felülre és alulra egy kis díszítés
	set slot (integers between {_first_row::first} and {_first_row::last}) of {_gui} to {config::shop::item::filler}
	set slot (integers between {_last_row::first} and {_last_row::last}) of {_gui} to {config::shop::item::filler}

	set (metadata "shop_gui_owner" of {_p}) to {_owner}
	set (metadata "shop_gui_page" of {_p})  to {_page}
	set (metadata "shop_gui_gui" of {_p})   to {_gui}

	shop_gui_refresh({_p}, {_page}, {_global})

	# Megnyitjuk a GUI-t
	open {_gui} to {_p}