function shop_entity_get(p: offlineplayer) :: entity:

	# Végigmegyünk az összes interaction entitáson
	loop all interactions:

		# Lekérdezzük az NBT-jét
		set {_nbt} to compound tag "custom" of nbt compound of loop-entity
		# Lekérdezzük a bolt tulajdonosát
		set {_owner} to string tag "Shop;Owner" of {_nbt}

		# Megnézzük, hogy az entitás egy bolthoz tartozik-e
		{_owner} is set
		
		# Ha a tulajdonos az a játékos akit keresünk
		if {_owner} = name of {_p}:
			# Visszaküldjük az entitást
			return loop-entity