function world_reset(world: text):
	
	loop all players where [input is in world({_world})]:
		
		spawn_teleport(loop-player)
		send server_feedback("warning", yaml value "messages.regenerating-warning" from "world-config") to loop-player
		
	server_log("world", yaml value "messages.regenerating" from "world-config")
		
	set {_env} to environment of {_world}
		
	world_delete({_world})
	world_create({_world}, {_env})