on load:

	loop all loaded yml:
		unload loop-value
		add 1 to {_num}

	broadcast "%{_num}%"

	# Globális konfigurációs fájl
	load yaml "plugins/Skript/scripts/kockacraft/configs/global-config.yml" as "global-config"

	# Komponens konfigurációs fájlok
	load yaml "plugins/Skript/scripts/kockacraft/configs/world-config.yml" as "world-config"
	load yaml "plugins/Skript/scripts/kockacraft/configs/server-config.yml" as "server-config"