on join:

	# Kikapcsoljuk a vanilla csatlakozási szöveget
	set join message to ""

	# Ha a játékos már játszott
	if player has played before:
		send action bar server_feedback("casual", "%display_name(player)% %{config::server::message::join}%", true) to all players

	# Játékos első csatlakozása
	else:
		send action bar server_feedback("casual", "%display_name(player)% %{config::server::message::new-join}%", true) to all players