options:
	first-join-message: "%display_name(player)% ßelőször jár itt! &8[#%number of offline players%&8]"

on first join:

	# Kikapcsoljuk a vanilla csatlakozási szöveget
	set join message to ""

	# Hozzáadjuk a játékos a "global" team-hez
	# Ez a saját Nametag rendszer miatt kell
	# Egyéb más dolgokra is alkalmas lehet
	add player to team named "global"
	nametag_create_entity(player)

	send action bar server_feedback("casual", {@first-join-message}, true) to all players