on server list ping:

	set {_motd::line::1} to text_center(yaml value "server.texts.motd" from "global-config", 124)
	set {_motd::line::2} to text_center(yaml value "server.texts.motd" from "global-config", 124)
	set {_motd::version} to yaml value "server.texts.version" from "global-config"

	set the motd to colored "%{_motd::line::1}% %nl% %{_motd::line::2}%"
	set version string to {_motd::version}