options:
	chance: 50%
	min-money: 5
	max-money: 30

function calculate_money(p: player, obj: object) :: number:

	# Ha nincs elmentve a "dupe" adat, akkor folytatjuk
	set {_nbt} to nbt compound of {_obj}
	if byte tag "dupe" of {_nbt} is not set:

		# x% esély
		if chance of {@chance}:
			# Egy random number-t (0.00) generálunk
			set {_random_money} to random number between {@min-money} and {@max-money}

	# Előbb létrehozott számot visszadobjuk
	return {_random_money}