options:
	create: &fRang létrehozása%nl%ßHasználat: &f/rang ßletrehoz ß<Rang> <Súly> <Prefix> <Chat color>
	delete: &fRang törlése%nl%ßHasználat: &f/rang ßtorol ß<Rang>
	add:    &fJátékosnak rang adás%nl%ßHasználat: &f/rang ßhozzaad &o%player% ß<Rang> <Időtartam>
	remove: &fJátékostól való rang elvétel%nl%ßHasználat: &f/rang ßelvesz &o%player%
	list:   &fKilistázza az összes játékost akinek van ragja%nl%ßHasználat: &f/rang ßlista

command /rang [<text>] [<text>] [<text>] [<text>] [<text>]:

	prefix: kockacraft
	executable by: console and players
	usage: &f/rang
	description: Ranggal kapcsolatos parancsok
	permission: rang
	trigger:

		if arg-1 = "letrehoz":
			ranks_create(player, arg-2, arg-3, arg-4, arg-5)

		else if arg-1 = "torol":
			ranks_delete(player, arg-2)

		else if arg-1 = "hozzaad":
			ranks_add(player, (arg-2 parsed as offline player), arg-3, (arg-4 parsed as timespan))

		else if arg-1 = "elvesz":
			ranks_remove(arg-2 parsed as offline player)
			
		else if arg-1 = "lista":
			ranks_list(player)

		else:
			send ""
			send formatted server_feedback("casual", "<tooltip:{@create}>/rang ßletrehoz <Rang> <Súly> <Prefix> <Chat color>")
			send formatted server_feedback("casual", "<tooltip:{@delete}>/rang ßtorol <Rang>", true)
			send formatted server_feedback("casual", "<tooltip:{@add}>/rang ßhozzaad <Játékos> <Rang> <Időtartam>", true)
			send formatted server_feedback("casual", "<tooltip:{@remove}>/rang ßelvesz <Játékos>", true)
			send formatted server_feedback("casual", "<tooltip:{@list}>/rang ßlista", true)
			send ""

on tab complete of "/rang":

	set tab completions for position 1 to "letrehoz", "torol", "hozzaad", "elvesz", "lista"

	if tab arg-1 = "letrehoz":
		set tab completions for position 2 to "<Rang>"
		set tab completions for position 3 to "<Súly>"
		set tab completions for position 4 to "<Prefix>"
		set tab completions for position 5 to "<Chat color>"

	if tab arg-1 = "torol":
		set tab completions for position 2 to all indices of {ranks::*}

	if tab arg-1 = "hozzaad":
		set tab completions for position 2 to all players
		set tab completions for position 3 to all indices of {ranks::*}
		set tab completions for position 4 to "<Időtartam>"

	if tab arg-1 = "elvesz":
		set tab completions for position 2 to all players
