# A 'ß' karakter a színkódot definíálja

messages:
  already-exist: "ß%{_world}% &cvilág be van töltve vagy már létezik!"
  not-exist: "ß%{_world}% &cvilág nincs betöltve vagy nem létezik!"

  successfully-created: "ß%{_world}% &fvilág létrehozva!"
  successfully-deleted: "ß%{_world}% &fvilág kitörölve!

  regenerating: "ß%{_world}% &fvilág újragenerálása..."
  regenerating-warning: "&6A ß%{_world}% &6világ újragenerálódik, ezért el lettél teleportálva!"

  teleport: "&fTeleportálás a(z) ß%{_world}% &fvilágba!"