function ranks_list(p: player):

	if size of indices of {rank::*} = 0:
		send server_feedback("warning", "&6Egy játékosnak sincs rangja!") to {_p}
		stop

	loop indices of {rank::*}:
		#{_player} isn't op

		set {_expire} to unix date of {rank::%loop-value%::expire} ? "&cVégleges"
		set {_target} to loop-value parsed as offlineplayer

		send server_feedback("casual", "%display_name({_target})% &f- ß%{_expire}%") to {_p}